#!/usr/bin/env bash
# Writes the licenses of everything the packaged app ships to
# THIRD-PARTY-NOTICES.txt. Run it (`pnpm notices`) after adding or upgrading a
# dependency and commit the result; test/third-party-notices.test.js fails when
# the file no longer matches package.json / pnpm-lock.yaml.
#
#   scripts/generate-third-party-notices.sh          rewrite the file
#   scripts/generate-third-party-notices.sh --check  exit 1 if it is out of date
#
# What ships, and therefore what is listed:
#   - Electron (the runtime itself). Chromium and the other components inside
#     Electron have their own notices file, LICENSES.chromium.html, which
#     Electron distributes with the runtime; it is referenced, not expanded.
#   - Production npm dependencies, transitively: electron-builder copies them
#     into the asar together with src/. Read from `pnpm list --prod`.
#   - Assets that come from devDependencies but still end up in the app:
#       bootstrap-icons  vendored as src/vendor/bootstrap-icons/ (version from
#                        its VERSION file, which must match node_modules)
#       tailwindcss      src/styles/app.css is generated by Tailwind and carries
#                        its preflight / base CSS
#     Add to EXTRA_PACKAGES below if another devDependency starts shipping.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"
CHECK=0
case "${1:-}" in
  "") ;;
  --check) CHECK=1 ;;
  *) echo "Usage: $0 [--check]" >&2; exit 2 ;;
esac

if [ ! -d node_modules ]; then
  echo "Error: node_modules is missing. Run: pnpm install" >&2
  exit 1
fi

# Created next to the output so the final mv is a rename, not a copy that could
# leave a truncated file behind if interrupted.
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

PROD_JSON=$(pnpm list --prod --depth Infinity --json)

PROD_JSON="$PROD_JSON" node - > "$TMP" <<'NODE'
const fs = require("fs");
const path = require("path");

// devDependencies whose code still ends up in the packaged app (see the header).
const EXTRA_PACKAGES = ["bootstrap-icons", "tailwindcss"];

const out = [];
const print = (line = "") => out.push(line);

function readPackage(dir) {
  return JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
}

function repositoryOf(pkg) {
  const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url;
  return repo || pkg.homepage || "";
}

function licenseFiles(dir) {
  // SPDX metadata such as LICENSE.spdx is not license text.
  return fs
    .readdirSync(dir)
    .filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f) && !/\.spdx$/i.test(f))
    .filter((f) => fs.statSync(path.join(dir, f)).isFile())
    .sort();
}

function entry(name, version, dir, pkg, note) {
  const repo = repositoryOf(pkg);
  print("=".repeat(80));
  print(`License: ${pkg.license}`);
  print("");
  print("Used by:");
  print(`  ${name} ${version}${repo ? ` (${repo})` : ""}`);
  print("");
  if (note) {
    print(note);
    print("");
  }
  const files = licenseFiles(dir);
  if (files.length === 0) {
    print("The package does not ship its license text; see the repository above.");
    print("");
    return;
  }
  for (const f of files) {
    if (files.length > 1) print(`--- ${f} ---`);
    print(fs.readFileSync(path.join(dir, f), "utf8").replace(/\r\n/g, "\n").replace(/\s+$/, ""));
    print("");
  }
}

function banner(title) {
  print("#".repeat(80));
  print(`# ${title}`);
  print("#".repeat(80));
  print("");
}

print("THIRD-PARTY NOTICES");
print("");
print("Side by Side Browser bundles the open source software listed below. Each entry");
print("gives the license, the packages it applies to, and the license text as shipped");
print("by the package. Generated by scripts/generate-third-party-notices.sh; do not");
print("edit by hand.");
print("");

// --- Electron -------------------------------------------------------------
banner("Electron and Chromium");
const electronDir = path.join("node_modules", "electron");
const electronPkg = readPackage(electronDir);
entry(
  "electron",
  electronPkg.version,
  electronDir,
  electronPkg,
  [
    "Electron embeds Chromium, Node.js and other components. Their licenses and",
    "notices are in LICENSES.chromium.html, which Electron distributes with the",
    "runtime (it is part of every Electron release archive, e.g.",
    `https://github.com/electron/electron/releases/tag/v${electronPkg.version}).`,
  ].join("\n"),
);

// --- JavaScript packages ----------------------------------------------------
banner("JavaScript packages (bundled into the app)");

const seen = new Map();
function walk(deps) {
  for (const [name, info] of Object.entries(deps || {})) {
    const key = `${name}@${info.version}`;
    if (!seen.has(key)) seen.set(key, { name, version: info.version, dir: info.path });
    walk(info.dependencies);
  }
}
for (const root of JSON.parse(process.env.PROD_JSON)) walk(root.dependencies);

for (const name of EXTRA_PACKAGES) {
  const dir = path.join("node_modules", name);
  const pkg = readPackage(dir);
  if (name === "bootstrap-icons") {
    const vendored = fs.readFileSync("src/vendor/bootstrap-icons/VERSION", "utf8").trim();
    if (vendored !== pkg.version) {
      console.error(
        `Error: src/vendor/bootstrap-icons is ${vendored} but node_modules has ${pkg.version}. ` +
          "Re-vendor it or align package.json before generating notices.",
      );
      process.exit(1);
    }
  }
  seen.set(`${name}@${pkg.version}`, { name, version: pkg.version, dir });
}

const packages = [...seen.values()].sort((a, b) =>
  a.name === b.name ? a.version.localeCompare(b.version) : a.name < b.name ? -1 : 1,
);
for (const p of packages) entry(p.name, p.version, p.dir, readPackage(p.dir));

process.stdout.write(out.join("\n").replace(/\n+$/, "") + "\n");
NODE

if [ "$CHECK" = 1 ]; then
  if cmp -s "$TMP" "$OUT"; then
    echo "$OUT is up to date"
    exit 0
  fi
  echo "Error: $OUT is out of date. Run: pnpm notices" >&2
  diff -u "$OUT" "$TMP" | head -40 >&2 || true
  exit 1
fi

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
